apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
      - name: my-react-app
        image: 698643712422.dkr.ecr.ap-south-1.amazonaws.com/my-react-app:latest
        ports:
        - containerPort: 80
